name = "cf-b2b"
main = "src/index.js"
compatibility_date = "2025-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "b2b_database"
database_id = "d96bdc2e-8209-4929-a3bc-44401553a80e"

# Environment variables
[vars]
ENVIRONMENT = "development"

# R2 Storage for images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "b2b-product-images"

[[kv_namespaces]]
binding = "STATIC_ASSETS" #
id = "669a4c71aaff4ebcaa34192f92d4b1c1" # 从 Cloudflare 获取的 KV Namespace ID
preview_id = "669a4c71aaff4ebcaa34192f92d4b1c1"
